pipeline:
  name: CI-CD
  identifier: CICD
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GithubSecret
        repoName: Microservices-Project
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: DockerHub
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: DockerHub
                    repo: " ajaytyagi0120118/nodejs-helloworld"
                    tags:
                      - v1
        delegateSelectors:
          - docker-delegate
        sendGitStatus:
          enabled: false
          name: ""
